image: gradle:6.6.1-jdk11

stages:
  - build
  - test

gradle-build:
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - gradle clean jar
  artifacts:
    paths:
      - build/libs/04-gvt-1.0.jar
  cache:
    key: gradle-cache
    paths:
      - .gradle/caches

acceptance:
  stage: test
  image: openjdk:11-jre-slim
  script:
    - src/test/acceptance/acc01.sh
    - src/test/acceptance/acc02.sh
    - src/test/acceptance/acc03.sh
    - src/test/acceptance/acc04.sh
    - src/test/acceptance/acc05.sh
    - src/test/acceptance/acc06.sh
    - src/test/acceptance/acc07.sh
    - src/test/acceptance/acc08.sh
    - src/test/acceptance/acc09.sh
    - src/test/acceptance/acc10.sh
